### ISSUE TITLE
Nested Mapper example

### ISSUE THREAD

**Issue by dreadjr** [MLSDev/TRON#13]
I have some json like the following.

`{
   "Devices":[
      {
         "id":1,
         "Attributes":[
            {
               "name":1
            },
            {
               "name":2
            }
         ]
      }
   ]
}`

I am not sure exactly how to map that to a swift class.

**Comment by DenTelezhkin** [comment]
Assuming you are using `JSONDecodable` and `APIRequest<[Device],...>`, you can do something like this:

``` swift
struct Device : JSONDecodable {
    let id: Int 
    let attributes: [Attribute]

    required init(json: JSON) {
        self.id = json["id"].intValue
        self.attributes = json["Attributes"].arrayValue.map { Attribute(json: $0 }
    }
}

struct Attribute: JSONDecodable {
    let name: Int

    required init(json: JSON) {
        self.name = json["name"].intValue
    }
}
```

It's possible, that you might need to use a wrapper instead of [Device] array, something like

``` swift
struct DevicesHolder : JSONDecodable 
{
    let devices: [Device]
    required init(json: JSON) {
        self.devices = json["Devices"].arrayValue.map { Device(json: $0) }
    }
}
```
