### ISSUE TITLE
How can help me with a full request example, including params, method and headers

### ISSUE THREAD

**Issue by Rojke34** [MLSDev/TRON#24]
Hi, I'm trying with this but I don't know 

`    
var tron = TRON(baseURL: "http://WebService.svc")

fileprivate func fecthMenu() {
        let params = [
            "apiSecretKey": "xxxxxxxxxxxxxxxx",
            "storeId": "1",
            "languageId": "1",
            "customerId": "0"
        ]

        //tron.headerBuilder = HeaderBuilder(defaultHeaders: ["Content-Type": "application/json; charset=utf-8"])

        let request : APIRequest<Menu,Error> = tron.request("/TopMenu")
        request.parameters = params
        //request.headers = ["Content-Type": "application/json; charset=utf-8"]
        request.method = .post

       request.perform(withSuccess: { zen in
            
            print(zen)
        }, failure: { error in
            
            print(error)
        })
       
    }`

And get this error 
**Alamofire.AFError.responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(400))**

Thanks.

**Comment by DenTelezhkin** [comment]
Well, you are getting 400 Error Status Code from your Back-End. This error is not coming from TRON or Alamofire.

You can contact your back-end developer, or check API documentation for your service, if you are doing everything right. Check HTTP method, headers, parameters, and other usual stuff.
