### ISSUE TITLE
Is the documentation still up to date? 

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#27]
I got this part right of the documentation but it throws an error 
> Cannot convert return expression of type 'APIRequest<_,_> to return type APIRequest<Assessment, MyAppError> 

Any idea what is wrong? 

I am using 

>  pod 'TRON', '~> 2.0.0'
> pod 'TRON/Core', '~> 2.0.0'
> pod 'TRON/RxSwift', '~> 2.0.0'

    import TRON

    struct Assessments {
    
        static let tron = TRON(baseURL: "https://api.myapp.com")
    
        static func read(id: Int) -> APIRequest<Assesment, MyAppError> {
            return tron.request("assessment")
        }
    }

**Comment by reshadf** [comment]
I am so sorry, I feel ashamed right now because just when I posted the issue I realised that Assessment was a struct where the MyAppError was a class. The fix was to convert Assessment to a class

**Comment by DenTelezhkin** [comment]
Glad that you figured everything out =) Just a quick note though: objects in TRON are not required to be classes, you can use structs if you need, and probably for data models it can be a good idea to prevent unwanted mutation.
