### ISSUE TITLE
Compatible error with xcode 8.2.1

### ISSUE THREAD

**Issue by ghost** [MLSDev/TRON#32]
When I tried to install Tron, it shows me this message in XCode : 

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

As Mentioned I'm using XCode Version 8.2.1 & Cocoapods 'TRON', '~> 2.0.0'
The different is, version of Alamofire was (4.2.0)in that time TRON was working fine, but for current version Alamofire (4.4.0) showing me mentioned error

**Comment by DenTelezhkin** [comment]
TRON 2.0 requires Swift 3, are you tryin to compile it with Swift 2.3?

**Comment by ghost** [comment]
I'm using Xcode 8 & Swift 3

**Comment by ghost** [comment]
The whole project build in swift 3, this issue appears only when I install TRON pod

**Comment by DenTelezhkin** [comment]
That's really weird, we are using TRON in multiple projects built in Swift 3 and never seen this issue. Maybe it's CocoaPods issue, what version are you using? It's recommended to use latest release version, right now it's 1.2.0, and there were some changes in 1.1.0 and 1.2.0 regarding SWIFT_VERSION settings.

**Comment by ghost** [comment]
Issue totally solved after update cocoapods to 1.2.0 

Thanks @DenHeadless
