### ISSUE TITLE
Problem with code=-999 Error, "Cancelled"

### ISSUE THREAD

**Issue by justindunn** [MLSDev/TRON#33]
I am switching from alamofire to TRON, I had my authentication code working just fine in AlamoFire, but when switching to TRON I'm getting this error 

`Error APIError<AuthorizationFailed>(request: Optional(http://192.168.1.32:3000/oauth/token), response: nil, data: Optional(0 bytes), error: Optional(Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=http://192.168.1.32:3000/oauth/token, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=http://192.168.1.32:3000/oauth/token})`

I have my plist to where currently it allows arbitrary loads, and like I said earlier I was able to make my API calls just fine when using only AlamoFire, I really like TRON though and want to convert so that I can make my life a little easier with API calls. here is the method's I've written:

`    let tron = TRON(baseURL: GlobalVariables().baseURL)
    
    class Authorized: JSONDecodable {
        required init(json: JSON) throws {
            DataController().Get(path: "/v1/users").perform(withSuccess: { (fetched) in
                  print("this is what i fetched", fetched)

            }) { (FetchFailed) in
                print("f*cked up")
            }
        }
    }
    
    class AuthorizationFailed: JSONDecodable {
        required init(json: JSON) throws {
            // code for failure
            print(json)
        }
    }
    
    func Authorize(parameters: [String:Any]) -> APIRequest<Authorized, AuthorizationFailed> {
        let AuthorizationRequest: APIRequest<Authorized, AuthorizationFailed> = tron.request("oauth/token")
        AuthorizationRequest.method = .post
        AuthorizationRequest.parameters = parameters
        return AuthorizationRequest
    }
    
    func AuthorizeUser(parameters: [String:Any]) {
        self.Authorize(parameters: parameters).perform(withSuccess: { (Authorized) in
            print("Success", Authorized)
        }) { (err) in
            print("Error", err)
            print(err.request) // Original URLRequest
            print(err.response) // HTTPURLResponse
            print(err.data) // Data of response
            print(err.error) // Error from Foundation Loading system
            print(err.errorModel.debugDescription) // MyAppError parsed property
        }
    }`

Thanks in advance for any help you guys can relay. Great work on the pod too btw.

**Comment by justindunn** [comment]
I don't know how to close this but i figured the issue out, thanks anyway!

**Comment by DenTelezhkin** [comment]
Don't worry, thanks for trying out our pod =)

**Comment by jayellos** [comment]
@justindunn how did you solved this issue? I'm getting the same error.
