### ISSUE TITLE
NetworkLoggerPlugin buildtime warnings

### ISSUE THREAD

**Issue by mgurreta** [MLSDev/TRON#34]
The following warnings appear when I compile my project with Xcode Version 8.3.1 (8E1000a):

/Pods/TRON/Source/Core/NetworkLoggerPlugin.swift:53:29: `Conditional downcast from 'Error?' to 'NSError' is a bridging conversion; did you mean to use 'as'?`

/Pods/TRON/Source/Core/NetworkLoggerPlugin.swift:56:36: `String interpolation produces a debug description for an optional value; did you mean to make this explicit?`

**Comment by DenTelezhkin** [comment]
Those warnings were fixed in 3.0.0 release. It's major because it has some breaking changes with plugins, but all other API is identical so update should be easy.

**Comment by mgurreta** [comment]
Ohh I see, thanks @DenHeadless (sorry)

**Comment by DenTelezhkin** [comment]
No problem =) Sometimes it's better to ask if something is not clear.
