### ISSUE TITLE
Multipart form data uploads not implemented and documentation is wrong.

### ISSUE THREAD

**Issue by Huralnyk** [MLSDev/TRON#37]
Example code how to make multipart form data upload differs from reality.

I couldn't find MultipartAPIRequest type in framework, please update documentation.

There is empty implementation for handling multipart requests in `func alamofireRequest(from manager: SessionManager) -> Request?`

`case .multipartFormData(_):
            return nil`

Is it going to be implemented in near future?

**Comment by DenTelezhkin** [comment]
Multipart requests **are** implemented, but they received significant changes, which you can read about in [2.0 Migration Guide](https://github.com/MLSDev/TRON/blob/master/Docs/2.0%20Migration%20Guide.md). The Readme is indeed, wrong, it seems like we forgot to update Multipart requests code to new syntax. We are going to update it, meanwhile take a look at [uploadMultipart method on TRON](https://github.com/MLSDev/TRON/blob/master/Source/Core/TRON.swift#L163), which is a new way to create `UploadAPIRequest` - replacement for MultipartAPIRequest in 1.0.

**Comment by Huralnyk** [comment]
So, why I always getting this, when I'm trying to perform just simple upload request?

```
let request: UploadAPIRequest<EmptyResponse, ApiError> = apiClient.tron.uploadMultipart("feedback") { formData in
    print(formData)
}

request.perform(withSuccess: { result in
    print("*** SUCCESS \(result)")
}, failure: { error in
    print("*** ERROR \(error)")
})
```

<img width="851" alt="screen shot 2017-05-31 at 4 38 21 pm" src="https://cloud.githubusercontent.com/assets/10194862/26634530/a8b86b62-461f-11e7-9747-ebebfe2ddf3c.png">

And there is empty implementation of multipartFormData request type handling in the function alamofireRequest(from manager: SessionManager) -> Request?

<img width="844" alt="screen shot 2017-05-31 at 4 39 22 pm" src="https://cloud.githubusercontent.com/assets/10194862/26634736/34dc0e0a-4620-11e7-8f38-0bc1dc173586.png">



Thanks in advance!

**Comment by Huralnyk** [comment]
I've got it. Sorry. I'm using wrong perform method. Should use performMultipart.

**Comment by DenTelezhkin** [comment]
Yeah, this should've failed much earlier, sorry about that.

To send multipart request, you need to use `performMultipart(withSuccess:failure:encodingMemoryThreshold:encodingCompletion:)` method:

```swift
let request: UploadAPIRequest<EmptyResponse, ApiError> = apiClient.tron.uploadMultipart("feedback") { formData in
    print(formData)
}

request.performMultipart(withSuccess: { result in
    print("*** SUCCESS \(result)")
}, failure: { error in
    print("*** ERROR \(error)")
})
```

This is because multipart requests are an exception to upload requests, and are handled differently and asynchronously by Alamofire. I will make sure that when `perform(withSuccess:failure:)` method is called and request type is `UploadRequestType.multipartFormData`, we should stop immediately and show appropriate error. I will reopen issue until i implement this. Again, sorry for inconvinience.
