### ISSUE TITLE
setting http headers isn't working

### ISSUE THREAD

**Issue by jonathan3087** [MLSDev/TRON#41]
I am using Xcode 8.3.3, TRON, Alamofire, SwiftyJSON.  I need to set my headers to ["Content-Type":"application/json"], I have tried both of the following:

request.headers = ["Content-Type":"application/json"]
and
let headers = request.headerBuilder.headers(forAuthorizationRequirement:
            AuthorizationRequirement.required,
            including: ["Content-Type":"application/json"])
request.headers = headers

neither of these options seems to make a difference, I still get a 400 or 405 server error and the logs show that the header is still: ["Accept":"application/json"], which I believe is the default according to the documentation.

Maybe I am misreading the docs and am trying to set the headers incorrectly.  Can anyone help or have any suggestions.

Thanks in advanced,
Jonathan

**Comment by DenTelezhkin** [comment]
Please post how you are creating request and sending it.

**Comment by jonathan3087** [comment]
I have the following code to make the request via TRON. According to the TRON Github page, I should be ae to set the header like this:

`request.headers` = ["Content-Type":"application/json"]

I have also tried:

request.headerBuilder.headers(forAuthorizationRequirement: AuthorizationRequirement.allowed, including: ["Content-Type":"application/json"])
I tried adding a few different ways of writing that, but nothing seems to work.

Here's a bigger section of the code so you can see the context

```
let urlSubfix = "\(Constant.REST_MOBILE)\(Constant.REGISTER)"
let request: APIRequest<RegisterApiResult, JSONError> = tron.request(urlSubfix)

request.method = .put

// request.headers = ["Content-Type":"application/json"]    
let header = request.headerBuilder.headers(forAuthorizationRequirement: AuthorizationRequirement.allowed, including: ["Content-Type":"application/json"])
request.headers = header

request.perform(withSuccess: { (registerApiResult) in
    print("Successfully fetched our json object")
    completion(registerApiResult)
}) { (err) in
    print("Failed to fetch json...", err)
}
```
Here is the actual error from my log:

> Failed to fetch json... APIError<JSONError>(request: Optional(http://www.slsdist.com/eslsd5/rest/mobileservice/register), response: Optional(<NSHTTPURLResponse: 0x618000028c20> { URL: http://www.slsdist.com/eslsd5/rest/mobileservice/register } { status code: 415, headers {
>     "Content-Length" = 0;
>     Date = "Sat, 22 Jul 2017 22:23:14 GMT";
>     Server = "Microsoft-IIS/7.5";
>     "X-Powered-By" = "Undertow/1, ASP.NET";
> } }), data: Optional(0 bytes), error: Optional(Alamofire.AFError.responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(415))), errorModel: Optional(Go_Cart.Service.JSONError))

As you can see I have tried to set the headers a couple different ways, but neither of them seems to take affect. Any help or advice from anyone would be helpful.

**Comment by DenTelezhkin** [comment]
It should work just by setting headers on request like so:

```swift
request.headers = ["Content-Type":"application/json"]  
```

You can try printing out resulting cURL of HTTP request like so:

```swift
let requestToken = request.perform(withSuccess: { (registerApiResult) in
    print("Successfully fetched our json object")
    completion(registerApiResult)
}) { (err) in
    print("Failed to fetch json...", err)
}

debugPrint(requestToken) // Will print out resulting cURL into console
```

This way you'll be able to see exactly what requests you are sending to your back-end. What you are receiving in response is response headers from the server, not request's. If headers are not on the request, please post resulting requests cURL to this issue, and we'll continue investigating this problem.

**Comment by jonathan3087** [comment]
It looks like the headers are being set correctly, so maybe it is my parameters.  I had used a print statement and thought that it looked correct, but now with the debugPrint statement, it looks smashed together as one field, but maybe that is how it is supposed to look.

Here's my code and the cURL response from my server.  Also, I can use the Postman Chrome plugin to call my API with this URL, header, and parms, and I get the response I am looking for.  Also, I have already built an Andorid app calling this same API and it is still working there as well.  So I really believe it is in the way I am setting up my parameters var now.  I am just trying to create a JSON object with a userID and password in it.  Should be pretty self-explainatory below.

`    func registerApi(completion: @escaping (RegisterApiResult) -> ()) {
        print("Register API Called")
        // URL should be: "http://www.slsdist.com/eslsd5/rest/mobileservice/register"
        
        let urlSubfix = "\(Constant.REST_MOBILE)\(Constant.STATUS)"
        
        let request: APIRequest<RegisterApiResult, JSONError> = tron.request(urlSubfix)
        
        let parameters: [String: Any] = [Constant.USER_ID: "jona",
                                         Constant.PASSWORD: "jonathan"]
        
        request.method = .put
        request.headers = ["Content-Type":"application/json"]
        request.parameters = parameters
        
        let requestToken = request.perform(withSuccess: { (registerApiResult) in
            print("Successfully fetched our json object")
            completion(registerApiResult)
        }) { (err) in
            print("Failed to fetch json...", err)
        }
        
        debugPrint(requestToken) // Will print out resulting cURL into console
        
    }`

Here's the response:

> Optional($ curl -v \
> 	-X PUT \
> 	-H "Content-Type: application/json" \
> 	-H "Accept-Language: en;q=1.0" \
> 	-H "Accept: application/json" \
> 	-H "User-Agent: Go Cart/1.0.0.1 (com.slsdist.Go-Cart; build:1; iOS 10.3.1) Alamofire/4.5.0" \
> 	-H "Accept-Encoding: gzip;q=1.0, compress;q=0.5" \
> 	-d "password=jonathan&userId=jona" \
> 	"http://www.slsdist.com/eslsd5/rest/mobileservice/register")
> JSON ERROR
> Failed to fetch json... APIError<JSONError>(request: Optional(http://www.slsdist.com/eslsd5/rest/mobileservice/register), response: Optional(<NSHTTPURLResponse: 0x600000031e60> { URL: http://www.slsdist.com/eslsd5/rest/mobileservice/register } { status code: 400, headers {
>     "Content-Length" = 211;
>     "Content-Type" = "text/html";
>     Date = "Tue, 25 Jul 2017 19:16:17 GMT";
>     Server = "Microsoft-IIS/7.5";
>     "X-Powered-By" = "Undertow/1, ASP.NET";
> } }), data: Optional(211 bytes), error: Optional(Alamofire.AFError.responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(400))), errorModel: Optional(Go_Cart.Service.JSONError))
>

**Comment by jonathan3087** [comment]
I previously posted the response log from a previous API call, not my "register" api.  I have corrected it an the log you see above is now from the correct call.

I can clearly see "Content-type: application/json" in the reponse from the curl.

But I am still getting a 400 level error from the server.  I guess it has something to do with:
"Alamofire.AFError.responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(400)), errorModel: Optional(Go_Cart.Service.JSONError)"

**Comment by DenTelezhkin** [comment]
Maybe your webserver expects parameters to be json encoded, since you have `Content-Type`:`application/json` set? In this case you can try changing encoding on the request:

```swift
request.parameterEncoding = JSONEncoding.default
```

This is using Alamofire framework, so you may want to `import Alamofire` in the top of the file.

**Comment by jonathan3087** [comment]
Was just looking for how to set the encoding.  Trying it now.

**Comment by jonathan3087** [comment]
YES! That did it, thank you so much for your help!!!!
