### ISSUE TITLE
Support for Codable protocol in Swift 4

### ISSUE THREAD

**Issue by DenTelezhkin** [MLSDev/TRON#42]

**Comment by reshadf** [comment]
Is there some progress on this @ the swift 4 branch? :)

**Comment by DenTelezhkin** [comment]
Yes, this is already implemented. I'm still thinking about how to release those features, because currently code in swift4.0 branch breaks backward compatibility with TRON 3.x. Also TRON depends on Alamofire, which itself will have a major release this fall.

I'm planning to release after Alamofire's release, so that those releases would be aligned, and TRON 4.x would work with Alamofire 5.x. This also applies to RxSwift and SwiftyJSON, but i don't expect any major changes there.

**Comment by DenTelezhkin** [comment]
Released 4.0.0-beta.1 version, that includes support for Codable.
