### ISSUE TITLE
How to use the plugins

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#46]
Hi, How do I use the protocols from https://github.com/MLSDev/TRON#plugins

to catch responses, errors etc. Can you give a code example? 

Currently I have something like this: 

    class APIHelper: Plugin {
    
    static var tron = TRON(baseURL: UserDefaults.standard.value(forKey: Constants.kAPIUrlUserDefaultsKey) as! String)
    
    func didReceiveDataResponse<Model, ErrorModel>(_ response: DataResponse<Model>, forRequest request: Request, formedFrom tronRequest: BaseRequest<Model, ErrorModel>) {
        print("response", response)
    }
    
    func didReceiveError<Model, ErrorModel>(_ error: APIError<ErrorModel>, forResponse response: (URLRequest?, HTTPURLResponse?, Data?, Error?), request: Request, formedFrom tronRequest: BaseRequest<Model, ErrorModel>) {
        print("error received", request)
    } 
    }

But I am not sure if that is correct since nothing is being outputted.

**Comment by DenTelezhkin** [comment]
You need to pass plugins either to TRON constructor to enable them globally like so:

```swift
let tron = TRON(baseURL: "https://api.myapp.com", plugins: [NetworkActivityPlugin()])
```

Or you can enable them on per-request basis, like so:

```swift
let request :APIRequest<Model,ErrorModel> = tron.request("foo")
request.plugins = [APIHelper()]
```
