### ISSUE TITLE
canceling requests

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#47]
Hi, I have not found any way in TRON to cancel requests.

Is there any API for that?

**Comment by DenTelezhkin** [comment]
Hey!

Sure, each performRequest method returns Alamofire.Request, which can be cancelled:

```swift
let token = request.perform(withSuccess: ..., failure: ...)

token.cancel()
```

If you use Rx extension for TRON, requests are also automatically cancelled when subscriptions get disposed.
