### ISSUE TITLE
Is there a way to access the header in the response?

### ISSUE THREAD

**Issue by jonathan3087** [MLSDev/TRON#50]
I am making my request just fine, using TRON (w/Alamofire) and SwiftyJSON.  I get the response body and it is parsed into the response model class I made for it, all working great.  What I need to do now is to get some fields from the response HEADER.  Is there any way to do that?  Thanks for any help in advance.  (BTW, I have searched for the past 2 hours, stackoverflow, github, google, asked co-worker).  I'm stumped.

**Comment by DenTelezhkin** [comment]
Well, you could make a plugin and attach it to request you wan't to get header from, however it would only work if header is needed separately from response. 

If you need to parse both model and header together, than you need to create a custom response serializer. Response serializer is defined as a typealias: 

```swift
typealias ResponseParser = (_ request: URLRequest?, _ response: HTTPURLResponse?, _ data: Data?, _ error: Error?) -> Result<Model>
```

You can see an example of response serializer implementation in SwiftyJSONDecodable, for example.

**Comment by jonathan3087** [comment]
I am such a Noob, that I don't know how to do either of those options.  I think I do want the header separately from the response, but I don't know how to make a plugin.  I will go search for info on how to create a plugin.  Thanks for your help.

**Comment by DenTelezhkin** [comment]
You can take a look at how currently available plugins are implemented - https://github.com/MLSDev/TRON/blob/master/Source/NetworkLoggerPlugin.swift

Or take a look at plugin ideas section in Docs - https://github.com/MLSDev/TRON/blob/master/Docs/PluginConcepts.md

Adding local plugin to your request is very simple, just call

```swift
request.plugins.append(YourPlugin())
``` 

As for custom response serializer, there is a dedicated doc for custom response serializers - https://github.com/MLSDev/TRON/blob/master/Docs/Response%20serializers.md

Hopefully this answers your question.

**Comment by jonathan3087** [comment]
Ah, yes, thank you for that info.
