### ISSUE TITLE
Send only a String value in the request body

### ISSUE THREAD

**Issue by uditha2233** [MLSDev/TRON#51]
Is it possible to POST just a string in the request body without using `[String: Any]` dictionary.
**Example:** I need to send `parameter = "Hello"` to the server instead of the `parameter = ["Key": "Hello"]`

**Comment by DenTelezhkin** [comment]
I would not recommend doing it, since most of back-ends support either key-value or json/xml input data.

However, if you really need or want to do it, you can implement custom ParameterEncoding and set it on APIRequest.

**Comment by uditha2233** [comment]
@DenHeadless Thanks for your response. Actually I cannot change anything in the backend side because it is not in my control. So I guess I have to use your second suggestion. If possible could you please give me an example on implementing custom ParameterEncoding?

**Comment by DenTelezhkin** [comment]
Sure, first of all take a look at the protocol itself and how Alamofire implements it for various data types:
https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L48

The custom encoding should look something like this:

```swift
struct SingleParameterEncoding: ParameterEncoding {
    let parameter: String
    init(parameter: String) {
        self.parameter = parameter
    }

    public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
        var urlRequest = try urlRequest.asURLRequest()
        urlRequest.httpBody = parameter.data(using: .utf8, allowLossyConversion: false)
        return urlRequest
    }
}
```

And then you set it on your APIRequest:

```swift
let request = tron.request("foo")
request.parameterEncoding = SingleParameterEncoding(parameter: "Hello")
```

**Comment by uditha2233** [comment]
@DenHeadless  Ok I'll try it. Thank You very much for your help.
