### ISSUE TITLE
stubbing network calls

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#52]
Hi, 

I am trying to write some tests for my network calls. However, they don't seem to reach the performStub function at all. Is there something I am doing wrong here? this is how my test looks like currently. 
```
    func testDataCanBeRetrieved() {
        
        let testBundle = Bundle(for: ProActiveTests.self)
        
        let request = self.coordinator.invoiceService.readAll()
        request.stubbingEnabled = true
        request.apiStub.stubDelay = 0.5
        request.apiStub.successful = true
        request.apiStub.buildModel(fromFileNamed: "invoices.json", inBundle: testBundle)
        request.apiStub.performStub(withSuccess: { (response) in
            print("response", response)
            XCTAssert(true)
        }) { (err) in
            print("Failure", err)
            XCTAssert(false)
        }
    }
```

**Comment by DenTelezhkin** [comment]
Not sure why it's not working for you, but you can actually use request.perform methods instead of calling stub directly. Other than that, code looks fine, you can try to debug if successful model is created from file.

**Comment by reshadf** [comment]
ah, the trick by using perform rather than the stub directly fixed it. Thanks.
