### ISSUE TITLE
Version 4 questions

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#53]
Hi, I have some questions that are not clear to me in the new beta version. I miss a codable error class example similar to the swiftyJSON version. 

```
class MyAppError : JSONDecodable {
  var errors: [String:[String]] = [:]

  required init(json: JSON) {
    if let dictionary = json["errors"].dictionary {
      for (key,value) in dictionary {
          errors[key] = value.arrayValue.map( { return $0.stringValue } )
      }
    }
  }
}
```

I have currently got the following: 
```
struct PAError: Decodable, Swift.Error {
    var errors: [String:[String]]
}
```

Is this the correct way?

**Comment by DenTelezhkin** [comment]
You should use `Codable` protocol instead of `Decodable`. And then it should work.

I've also added small documentation section in readme, that shows how to use our `Codable` implementation - https://github.com/MLSDev/TRON/blob/master/README.md#codable.
