### ISSUE TITLE
Intercept requests and change response

### ISSUE THREAD

**Issue by vegidio** [MLSDev/TRON#56]
Is it possible to intercept a request using Plugins and change the request before it continues? Or maybe intercept a request and send a pre-defined response to the user?

**Comment by DenTelezhkin** [comment]
Yeah, you can modify request to some extent using Plugins: https://github.com/MLSDev/TRON/blob/master/Source/Plugin.swift#L44

As for sending pre-defined response, you can take a look at network stubs https://github.com/MLSDev/TRON#stubbing. Currently it's not possible to switch request type from usual request to stubbed one. Can i ask you about your use case, why do you need that?
