### ISSUE TITLE
How to print out the request string?

### ISSUE THREAD

**Issue by jhseung** [MLSDev/TRON#58]
I'm trying to debug my app, and I need access to the url of the apirequest. 
request.path isn't working

**Comment by DenTelezhkin** [comment]
You can print out complete cURL of the Alamofire.Request by using debugPrint:

```swift
let alamofireRequest = request.perform(withSuccess: { _ in }, failure: { _ in })
debugPrint(alamofireRequest)
```

or alternatively, you can use NetworkLoggerPlugin, which does the same thing:
https://github.com/MLSDev/TRON/blob/master/Source/NetworkLoggerPlugin.swift
