### ISSUE TITLE
CocoaPods compatible version error

### ISSUE THREAD

**Issue by rubaiet** [MLSDev/TRON#59]
When I tried to install TRON 4.0 via CocoaPods, terminal shows these errors:

```
CocoaPods could not find compatible versions for pod "TRON":
  In Podfile:
    TRON (~> 4.0)

None of your spec sources contain a spec satisfying the dependency: `TRON (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I did upgraded my project from Swift 3.2 to 4.0.
Right now using xcode 9.1 and Swift 4.0.

I already tried the below methods
```
pod repo remove master
pod setup
pod install
```

`pod repo update`

**Comment by DenTelezhkin** [comment]
Sorry, README is currently misleading, 4.0.0 release has not yet been cut, you can use 4.0.0-beta.2 release for now. I'm planning to make release soon, will update this issue when it will be done.

**Comment by DenTelezhkin** [comment]
4.0.0 release has been made - https://github.com/MLSDev/TRON/releases/tag/4.0.0

Closing.
