### ISSUE TITLE
MultipartAPIRequest && Int Parameters have errors

### ISSUE THREAD

**Issue by arden** [MLSDev/TRON#6]
when i'm use MultipartAPIRequest and Int Parameters that:

let request: MultipartAPIRequest<APIResponse, APIResponseError> = tron.multipartRequest(path: "/social/login")

request.parameters = ["nickname": nickname, "socialUid": socialUid, "socialToken": socialToken, "socialSource": String(socialSource), "sex" : String(sex), "uuid": uuid, "pushToken": pushToken, "source": String(source)]

if the parameters have Int types, this post have some errors, must be convert the Int to String.

formData.appendBodyPart(data: value.dataUsingEncoding(NSUTF8StringEncoding) ?? NSData(), name: key)

Int types have no dataUsingEncoding method.

**Comment by DenTelezhkin** [comment]
Hey!

Indeed, this is a bug. I wonder, why Swift even allows calling this method on AnyObject var.

I've pushed a fix in d13beed837357dbf19177980c41eb2d6f593f22f, and released [0.4.3 version](https://github.com/MLSDev/TRON/releases/tag/0.4.3) with it.
