### ISSUE TITLE
ParameterEncoding

### ISSUE THREAD

**Issue by igormagurean** [MLSDev/TRON#65]
How to send in post request, parameters that are encoded as URLEncoding.queryString, and other parameters are encoded as JSONEncoding.default - in one request?!
So, post request will be with body and with some parameters encoded in url
https://anyurl.com/?userId=0 and + body for this request?

**Comment by DenTelezhkin** [comment]
For that, you would need to implement [custom ParameterEncoding](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#custom-encoding). And then you can set it on request:

```swift
request.parameterEncoding = CustomParameterEncoding(...)
```

**Comment by igormagurean** [comment]
Thank you for the answer, but can you give me another example please..
I need to encode userId=0 as URLEncoding and already encoded dictionary into HTTPBODY

```
var dictionary: [String: Any] {
    return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] ?? [:]
  }
```

**Comment by igormagurean** [comment]
I dont understand how to encode parameters in URL, in httpBody it's understandable..

**Comment by DenTelezhkin** [comment]
For example, in your case, custom response serializer may include dictionary of values, and possibly body data to be encoded in URL:

```swift
struct CustomURLParameterEncoding: ParameterEncoding {
	private let dictionary: [String:Any]
        private let bodyData: Data

    init(dictionary: [String:Any], bodyData: Data) {
        self.dictionary = dictionary
    }

    func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
        var urlRequest = try urlRequest.asURLRequest()

        if var urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: false), !dictionary.isEmpty {
                let percentEncodedQuery = (urlComponents.percentEncodedQuery.map { $0 + "&" } ?? "") + query(dictionary)
                urlComponents.percentEncodedQuery = percentEncodedQuery
                urlRequest.url = urlComponents.url
            }
        urlRequest.httpBody = bodyData
        return urlRequest
    }
}
```

Some of the code was copypasted, so sorry if it does not work, you would need to check syntax and other things. Hope this explains the idea. The code to create key value pairs in URL was taken from [here](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L184-L188).
