### ISSUE TITLE
TRON tag on stackoverflow seems to pertain to a blockchain project

### ISSUE THREAD

**Issue by lk251** [MLSDev/TRON#68]
How then to tag a post for support on Stackoverflow? It's about a breaking change involving ErrorSerializable and JSONDecodable. Thank you.

**Comment by DenTelezhkin** [comment]
Hey!

You can add an additional tag, like Swift or networking or something like that.

If your question is about TRON 5.0 beta, there will be a migration guide before final version comes out. I'm waiting for Alamofire final 5.0 release to incorporate their migration guide and TRON migration guide. Specifically `ErrorSerializable` aims at flattening out error types from `APIError<ErrorModel>` to a single type that contains all HTTP request information as well as parsed model, which was hard to do in previous releases.
